### ISSUE TITLE
Read in FASTA formatted file

### ISSUE THREAD

**Issue by MikeDeberg** [MikeDeberg/CustomMemoryManagement#5]
Example FASTA format:

```
>some_kind;of|id Human description
SEQUENCEATCGTCGATC
```

A single FASTA file will be stored as an arrary of structs
Each read will be stored as a struct in this array contains fields for ID, Description, and Sequence.

**Comment by MikeDeberg** [comment]
Ill get working on this

**Comment by MikeDeberg** [comment]
I will use a file pointer passed back and forth between a reading function that will allow a single FASTA header:sequence struct to be returned with every call of the reading function.

**Comment by ebolyen** [comment]
:+1:

**Comment by MikeDeberg** [comment]
Able to read in from FASTA file one record at a time using ifstream.
